-- Superseded by schema.sql: the `priority_votes` view now lives there
-- (built from submissions/submission_choices instead of the old
-- auth.users-linked buy_order_submissions table). Nothing to run here --
-- this file is kept only as a pointer so it doesn't go stale silently.
